blog/urls.py
from django.urls import path

from . import views

app_name = 'weblog'
urlpatterns = [
    path(
        '<int:year>/<str:month>/<int:day>/<slug>/',
        views.BlogDateDetailView.as_view(),
        name="entry"
    ),
    path(
        '<int:year>/<str:month>/<int:day>/',
        views.BlogDayArchiveView.as_view(),
        name="archive-day"
    ),
    path(
        '<int:year>/<str:month>/',
        views.BlogMonthArchiveView.as_view(),
        name="archive-month"
    ),
    path(
        '<int:year>/',
        views.BlogYearArchiveView.as_view(),
        name="archive-year"
    ),
    path(
        '',
        views.BlogArchiveIndexView.as_view(),
        name="index"
    ),
]

fundraising/urls.py
from django.urls import path

from . import views

app_name = 'fundraising'
urlpatterns = [
    path('', views.index, name='index'),
    path('donation-session', views.configure_checkout_session, name='donation-session'),
    path('thank-you/', views.thank_you, name='thank-you'),
    path('manage-donations/<hero>/', views.manage_donations, name='manage-donations'),
    path('manage-donations/<hero>/cancel/', views.cancel_donation, name='cancel-donation'),
    path('receive-webhook/', views.receive_webhook, name='receive-webhook'),
    path('update-card/', views.update_card, name='update-card'),
]

fundraising/forms.py
import stripe
from captcha.fields import ReCaptchaField
from captcha.widgets import ReCaptchaV3
from django import forms
from django.utils.safestring import mark_safe

from .models import (
    INTERVAL_CHOICES, LEADERSHIP_LEVEL_AMOUNT, DjangoHero, Donation,
)


class DjangoHeroForm(forms.ModelForm):
    hero_type = forms.ChoiceField(
        required=False,
        widget=forms.RadioSelect,
        label='I am donating as an',
        choices=DjangoHero.HERO_TYPE_CHOICES,
        initial=DjangoHero.HERO_TYPE_CHOICES[0][0],
    )
    name = forms.CharField(
        required=False,
        widget=forms.TextInput(
            attrs={
                'class': 'required',
                'placeholder': 'Your name or the name of your organization',
            },
        )
    )
    location = forms.CharField(
        required=False,
        widget=forms.TextInput(
            attrs={
                'placeholder': 'Where are you located? (optional; will not be displayed)',
            },
        )
    )
    url = forms.CharField(
        required=False,
        widget=forms.TextInput(
            attrs={
                'placeholder': 'Which URL should we link your name to?',
            },
        )
    )
    logo = forms.FileField(
        required=False,
        help_text=(
            "If you've donated at least US $%d, you can submit your logo and "
            "we will display it, too." % LEADERSHIP_LEVEL_AMOUNT
        ),
    )
    is_visible = forms.BooleanField(
        required=False,
        label=(
            "Yes, display my name, URL, and logo on this site. "
            "It'll be displayed shortly after we verify it."
        ),
    )
    is_subscribed = forms.BooleanField(
        required=False,
        label=(
            'Yes, the Django Software Foundation can inform me about '
            'future fundraising campaigns by email.'
        ),
    )

    class Meta:
        model = DjangoHero
        fields = (
            'hero_type', 'name', 'location', 'url', 'logo', 'is_visible',
            'is_subscribed',
        )

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.checkbox_fields = []
        self.radio_select_fields = []

        for name, field in self.fields.items():
            if isinstance(field.widget, forms.CheckboxInput):
                self.checkbox_fields.append(name)
            elif isinstance(field.widget, forms.RadioSelect):
                self.radio_select_fields.append(name)

    def save(self, commit=True):
        hero = super().save(commit=commit)
        customer = stripe.Customer.retrieve(hero.stripe_customer_id)
        customer.description = hero.name or None
        customer.email = hero.email or None
        customer.save()
        return hero


class StripeTextInput(forms.TextInput):
    """
    Inspired by widgets in django-zebra
    """
    def _add_data_stripe_attr(self, name, kwargs):
        kwargs.setdefault('attrs', {}).update({'data-stripe': name})
        return kwargs

    def _strip_name_attr(self, widget_string, name):
        return widget_string.replace("name=\"%s\"" % (name,), "")

    def render(self, name, *args, **kwargs):
        kwargs = self._add_data_stripe_attr(name, kwargs)
        rendered = super().render(name, *args, **kwargs)
        return mark_safe(self._strip_name_attr(rendered, name))


class DonateForm(forms.Form):
    """
    Used to generate the HTML form in the fundraising page.
    """
    AMOUNT_CHOICES = (
        (25, 'US $25'),
        (50, 'US $50'),
        (100, 'US $100'),
        (250, 'US $250'),
        (500, 'US $500'),
        (750, 'US $750'),
        (1000, 'US $1,000'),
        (1250, 'US $1,250'),
        (2500, 'US $2,500'),
        ('custom', 'Other amount'),
    )

    amount = forms.ChoiceField(choices=AMOUNT_CHOICES)
    interval = forms.ChoiceField(choices=INTERVAL_CHOICES)
    captcha = ReCaptchaField(widget=ReCaptchaV3)


class DonationForm(forms.ModelForm):
    """
    Used in the manage donations view.
    """
    subscription_amount = forms.DecimalField(max_digits=9, decimal_places=2, required=True)
    # here we're removing "onetime" option from interval choices:
    interval = forms.ChoiceField(choices=INTERVAL_CHOICES[:3], required=True)

    class Meta:
        model = Donation
        fields = ('subscription_amount', 'interval')

    def save(self, commit=True, *args, **kwargs):
        donation = super().save(commit=commit)
        interval = self.cleaned_data.get('interval')
        amount = self.cleaned_data.get('subscription_amount')

        # Send data to Stripe
        customer = stripe.Customer.retrieve(donation.stripe_customer_id)
        subscription = customer.subscriptions.retrieve(donation.stripe_subscription_id)
        # TODO: Setting the plan is deprecated — use Price API instead.
        subscription.plan = interval
        subscription.quantity = int(amount)

        subscription.save()

        return donation


class PaymentForm(forms.Form):
    """
    Used to validate values when configuring the Stripe Session.

    `amount` can be any integer, so a ChoiceField is not appropriate.
    """
    captcha = ReCaptchaField(widget=ReCaptchaV3)
    amount = forms.IntegerField(
        required=True,
        min_value=1,  # Minimum payment from Stripe API
        max_value=1_000_000,  # Reject clearly unrealistic amounts.
    )
    interval = forms.ChoiceField(
        required=True,
        choices=INTERVAL_CHOICES,
    )

fundraising/views.py
import decimal
import json
import logging

import stripe
from django.conf import settings
from django.contrib import messages
from django.core.mail import send_mail
from django.forms.models import modelformset_factory
from django.http import HttpResponse, JsonResponse
from django.shortcuts import get_object_or_404, redirect, render
from django.template.loader import render_to_string
from django.urls import reverse
from django.views.decorators.cache import never_cache
from django.views.decorators.csrf import csrf_exempt
from django.views.decorators.http import require_POST

from .forms import DjangoHeroForm, DonationForm, PaymentForm
from .models import DjangoHero, Donation, Payment, Testimonial

logger = logging.getLogger(__name__)


def index(request):
    testimonial = Testimonial.objects.filter(is_active=True).order_by('?').first()
    return render(request, 'fundraising/index.html', {
        'testimonial': testimonial,
    })


@require_POST
def configure_checkout_session(request):
    """
    Configure the payment session for Stripe.
    Return the Session ID.

    Key attributes are:

    - mode: payment (for one-time charge) or subscription
    - line_items: including price_data because users configure the donation
                  price.

    TODOs

    - Standard amounts could use active Prices, rather than ad-hoc price_data.
    - Tie Stripe customers to site User accounts.
      - If a user is logged in, we can create the session for the correct
        customer.
      - Stripe's documented flows are VERY keen that we create the customer
        first, although the session will do that if we don't.
    - Allow selecting currency. (Smaller task.) Users receive an additional
      charge making payments in foreign currencies. Stripe will convert all
      payments without further charge.
    """

    # Form data:
    # - The interval: which determines the Product and the mode.
    # - The amount: which goes to the Price data.
    form = PaymentForm(request.POST)
    if not form.is_valid():
        data = {
            'success': False,
            'error': form.errors
        }
        return JsonResponse(data)

    amount = form.cleaned_data["amount"]
    interval = form.cleaned_data["interval"]

    product_details = settings.PRODUCTS[interval]
    is_subscription = product_details.get('recurring', True)

    price_data = {
        'currency': 'usd',
        'unit_amount': amount * 100,
        'product': product_details['product_id']
    }
    if is_subscription:
        price_data['recurring'] = {
            'interval': product_details['interval'],
            "interval_count": product_details["interval_count"],
        }

    try:
        session = stripe.checkout.Session.create(
            payment_method_types=['card'],
            line_items=[{'price_data': price_data, 'quantity': 1}],
            mode='subscription' if is_subscription else 'payment',
            success_url=request.build_absolute_uri(
                reverse('fundraising:thank-you')
            ),
            cancel_url=request.build_absolute_uri(
                reverse('fundraising:index')
            ),
            # TODO: Drop this when updating API.
            stripe_version="2020-08-27",
        )

        return JsonResponse({'success': True, "sessionId": session["id"]})
    except Exception as e:
        logger.exception('Error configuring Stripe session.')
        return JsonResponse({'success': False, "error": str(e)})


def thank_you(request):
    """
    Generic thank you page. In theory only reached via successful payment, but
    no information is passed from Stripe to be sure.
    """
    return render(request, 'fundraising/thank-you.html', {})


# TODO: Use Stripe's customer portal.
@never_cache
def manage_donations(request, hero):
    hero = get_object_or_404(DjangoHero, pk=hero)
    recurring_donations = hero.donation_set.exclude(stripe_subscription_id='')
    past_payments = Payment.objects.filter(donation__donor=hero).select_related('donation')

    ModifyDonationsFormset = modelformset_factory(Donation, form=DonationForm, extra=0)

    if request.method == 'POST':
        hero_form = DjangoHeroForm(
            data=request.POST,
            files=request.FILES,
            instance=hero,
        )
        modify_donations_formset = ModifyDonationsFormset(
            request.POST,
            queryset=recurring_donations
        )

        if hero_form.is_valid() and modify_donations_formset.is_valid():
            hero_form.save()
            modify_donations_formset.save()
            messages.success(request, "Your information has been updated.")
    else:
        hero_form = DjangoHeroForm(instance=hero)
        modify_donations_formset = ModifyDonationsFormset(
            queryset=recurring_donations
        )

    return render(request, 'fundraising/manage-donations.html', {
        'hero': hero,
        'hero_form': hero_form,
        'modify_donations_formset': modify_donations_formset,
        'recurring_donations': recurring_donations,
        'past_payments': past_payments,
        'stripe_publishable_key': settings.STRIPE_PUBLISHABLE_KEY,
    })


@require_POST
def update_card(request):
    donation = get_object_or_404(Donation, id=request.POST['donation_id'])
    try:
        customer = stripe.Customer.retrieve(donation.stripe_customer_id)
        subscription = customer.subscriptions.retrieve(donation.stripe_subscription_id)
        subscription.source = request.POST['stripe_token']
        subscription.save()
    except stripe.error.StripeError as e:
        data = {'success': False, 'error': str(e)}
    else:
        data = {'success': True}
    return JsonResponse(data)


@require_POST
def cancel_donation(request, hero):
    donation_id = request.POST.get('donation')
    hero = get_object_or_404(DjangoHero, pk=hero)
    donations = hero.donation_set.exclude(stripe_subscription_id='')
    donation = get_object_or_404(donations, pk=donation_id)

    customer = stripe.Customer.retrieve(donation.stripe_customer_id)
    customer.subscriptions.retrieve(donation.stripe_subscription_id).delete()

    donation.stripe_subscription_id = ''
    donation.save()

    messages.success(request, "Your donation has been canceled.")
    return redirect('fundraising:manage-donations', hero=hero.pk)


@require_POST
@csrf_exempt
def receive_webhook(request):
    try:
        data = json.loads(request.body.decode())
    except ValueError:
        return HttpResponse(422)

    # For security, re-request the event object from Stripe.
    # TODO: Verify shared secret here?
    try:
        event = stripe.Event.retrieve(data['id'])
    except stripe.error.InvalidRequestError:
        return HttpResponse(422)

    return WebhookHandler(event).handle()


class WebhookHandler:
    def __init__(self, event):
        self.event = event

    def handle(self):
        handlers = {
            'invoice.payment_succeeded': self.payment_succeeded,
            'invoice.payment_failed': self.payment_failed,
            'customer.subscription.deleted': self.subscription_cancelled,
            'checkout.session.completed': self.checkout_session_completed,
        }
        handler = handlers.get(self.event.type, lambda: HttpResponse(422))
        return handler()

    def payment_succeeded(self):
        invoice = self.event.data.object
        # Ensure we haven't already processed this payment
        if Payment.objects.filter(stripe_charge_id=invoice.charge).exists():
            # We need a 2xx response otherwise Stripe will keep trying.
            return HttpResponse()
        donation = get_object_or_404(
            Donation, stripe_subscription_id=invoice.subscription)
        amount = decimal.Decimal(invoice.total) / 100
        if invoice.charge:
            donation.payment_set.create(amount=amount, stripe_charge_id=invoice.charge)
        return HttpResponse(status=201)

    def subscription_cancelled(self):
        subscription = self.event.data.object
        donation = get_object_or_404(
            Donation, stripe_subscription_id=subscription.id)
        donation.stripe_subscription_id = ''
        donation.save()

        mail_text = render_to_string(
            'fundraising/email/subscription_cancelled.txt', {'donation': donation})
        send_mail('Payment cancelled', mail_text,
                  settings.DEFAULT_FROM_EMAIL, [donation.donor.email])

        return HttpResponse(status=204)

    def payment_failed(self):
        invoice = self.event.data.object
        donation = get_object_or_404(
            Donation, stripe_subscription_id=invoice.subscription)

        mail_text = render_to_string(
            'fundraising/email/payment_failed.txt', {'donation': donation})
        send_mail('Payment failed', mail_text,
                  settings.DEFAULT_FROM_EMAIL, [donation.donor.email])

        return HttpResponse(status=204)

    def get_donation_interval(self, session):
        """
        Helper to determine Donation.interval from completed Stripe Session.
        """
        if session.mode == 'payment':
            return 'onetime'

        # Access the interval via the attached price object.
        # See https://stripe.com/docs/api/subscriptions/object
        # TODO: remove stripe_version when updating account settings.
        subscription = stripe.Subscription.retrieve(session.subscription, stripe_version="2020-08-27")
        recurrance = subscription["items"].data[0].price.recurring
        if recurrance.interval == 'year':
            return 'yearly'
        elif recurrance.interval_count == 3:
            return 'quarterly'
        else:
            return 'monthly'

    def checkout_session_completed(self):
        """
        > Occurs when a Checkout Session has been successfully completed.
        https://stripe.com/docs/api/events/types#event_types-checkout.session.completed
        """
        session = self.event.data.object

djangoproject/templates/fundraising/index.html
{% extends 'base.html' %}
{% load fundraising_extras humanize static %}

{% block title %}Support Django{% endblock %}
{% block layout_class %}full-width{% endblock %}

{% block header %}
<h1 class="visuallyhidden">Support Django</h1>
<p><em>Support Django development</em> by donating to the <em>Django Software Foundation</em>.</p>
{% endblock %}

{% block messages %}

  {% if messages %}
    {% for message in messages %}
    <h1>{{ message }}</h1>
    {% endfor %}
    <hr>
  {% endif %}

{% endblock %}

{% block content %}

<h1>Support the Django Software Foundation!</h1>

{% donation_form_with_heart %}
  
<h1>Other ways to give</h1>
<ul>
  <li><a href="https://django.threadless.com/" target="_blank">Official merchandise store</a> - 
    Buy official t-shirts, accessories, and more to support Django.</li>
  <li><a href="https://github.com/sponsors/django" target="_blank">Sponsor Django via GitHub Sponsors</a>.</li>
  <li><a href="/foundation/donate/#amazon-smile">Amazon Smile</a> - When you
    shop at Amazon, you can nominate for 0.5% of the purchase price of your
    eligible purchases to be donated to the DSF.</li>
  <li><a href="/foundation/donate/#benevity-giving">Benevity Workplace Giving
    Program</a> - If your employer participates, you can make donations to the
    DSF via payroll deduction.</li>
</ul>

<h2 id="why-give">Why give to the Django Software Foundation?</h2>

<p>Our main focus is direct support of Django's developers. This means:</p>
<ul>
<li>Organizing and funding development sprints so that Django's developers can
meet in person.</li>
<li>Helping key developers attend these sprints and other community events by
covering travel expenses to official Django events.</li>
<li>Providing financial assistance to community development and outreach
projects such as <a href="#django-girls">Django Girls</a>.</li>
<li>Providing financial assistance to individuals so they can attend major
conferences and events.</li>
<li>Funding the <a href="#fellowship-program">Django Fellowship program</a>,
which provides full-time staff to perform community management tasks in the
Django community.</li>
</ul>

<p>Still curious? See our <a href="/foundation/donate/">Frequently Asked Questions</a>
about donations.</p>

<h2 id="fellowship-program">Django Fellowship Program</h2>

<p>The biggest expense of the <abbr title="Django Software Foundation">DSF</abbr>
  is the Django Fellowship program. It's a project where
  <a href="#who-are-the-django-fellows">paid contractors</a> are engaged to
  manage some of the administrative and community management tasks of the
  Django project to support rapid development of Django itself.</p>

<p><strong>The Django Fellowship program has a major positive impact on how
  Django is developed and maintained.</strong>
  The Django Fellows triage 10-15 new tickets each week and review and merge
  around fifteen non-trivial patches a week from the community. Release
  blocking and severe bugs aren't postponed indefinitely. Major releases happen
  according to an 8 month schedule and bug fix releases occur monthly.</p>

<p>For more details, you can read retrospectives for the
  <a href="/weblog/2015/jan/21/django-fellowship-retrospective/"> first three
  months of the program</a>,
  <a href="/weblog/2015/dec/17/fellowship-2015-retrospective/">2015</a>, and
  <a href="/weblog/2016/dec/28/fellowship-2016-retrospective/">2016</a>.
</p>

<p>The Django Fellows are a resource to help review patches and contributions
   from the community, and the community loves that:</p>

   {% if testimonial %}
   <blockquote>
     {{ testimonial.body|linebreaks }}
     <em>{{ testimonial.author }}</em>
   </blockquote>
   {% endif %}

<p><strong>If you use Django on a daily basis and care about the development of Django
   itself, you should donate today</strong> (may be <a href="/foundation/donate/#tax-deductible">tax deductible</a>).
   Only with your support can we make sure that the Web framework you base your work on
   can grow to be even better in the coming years.</p>

<h2 id="django-girls">Django Girls Outreach</h2>

<p>Supporting <a href="https://djangogirls.org/">Django Girls workshops</a> is
a significant priority for the Django Software Foundation. Django Girls
workshops are organized by volunteers and are provided as free events for women
who want to learn to code. The workshop serves as an introduction to Python and
Django, where attendees learn usable skills to build their first web app.</p>

<p>Django Girls workshop attendees go on to organize their own workshops, lead
in their community, and secure full-time jobs as developers. Read their stories
in the “Your Django Story” series on the <a href="http://blog.djangogirls.org/">
Django Girls blog</a>.</p>

<p>In 2015, the Django Software Foundation contributed $5,400 to eighteen
Django Girls workshops around the world. Here's what some of the organizers had
to say about the impact:</p>

<blockquote>
<p>Sponsorship from the DSF allowed us to have on-site child care for our Django
Girls Portland workshop. We hosted 2 young children and an infant, and provided
them with healthy snacks, games, sidewalk chalk, finger paint, and emoji
stickers. Without our nanny, 3 of our attendees wouldn't have been able to come
to the workshop. Finger paint photo is
<a href="http://blog.djangogirls.org/post/124680859493/django-girls-portland-a-retrospective">
on the blog</a>!</p>
<em>Lacey - Portland, Oregon, US</em>
</blockquote>

<blockquote>
<p>The DSF supported <a href="https://djangogirls.org/warsaw/">Django Girls
Poland</a> four times this year and the impact was enormous! In Poland, diversity
awareness is not a very common topic. When we approached different local
companies about our workshops they usually didn't get what we were actually
doing and why it is important. If not for the DSF, we probably would not have
been able to hold our workshops at all. Our first workshops were the only until
now workshops that were 100% female - female only coaches and female only
attendees. Thanks to you, we were able to focus on gathering female mentors
instead of searching for sponsors!</p>
<em>Ania - Wrocław, Poland</em>
</blockquote>

<blockquote>
<p><a href="https://pyfound.blogspot.kr/2015/10/django-girls-seoul-great-success.html">
Django Girls Seoul</a> had 425 applicants from 11 different countries ages
ranging from 16 to 50 years old. After acceptances, we had about 105 people to
feed and caffeinate! Thanks to Django's sponsorship we could get all of our
participants coffee for the day. It really made a huge difference because we
all know how a cup of coffee can change the atmosphere and mood! We were so
grateful to the sponsorship we received from abroad. We tried to get sponsorship
from a lot of Korean companies but the same generosity doesn't translate well
into a Korean Business culture, I guess. This made us even more thankful for
our friends at the DSF!</p>
<em>Rachell - Seoul, South Korea</em>
</blockquote>

<hr style="margin: 40px 0" />

<div class="heroes-section">
  <h1>DSF Supporters</h1>
  <p>Our donors make our work possible! We are incredibly grateful for the
  financial support from the following individuals and organizations in our
  community.</p>

  {% display_django_heroes %}
</div>
{% endblock %}

{% block content-extra %}
  <div class="layout-tertiary" id="about">
    <div class="container">
      <h2>What is the Django Software Foundation?</h2>
      <p>Development of Django is supported by an independent foundation
        established as a 501(c)(3) non-profit. Like most open-source foundations,
        the goal of the <a href="/foundation/">Django Software Foundation</a>
        is to promote, support, and advance the Django Web framework. If you're
        interested in how the Django Software Foundation supports the Django
        Web framework, we published a
        <a href="/weblog/2015/jan/08/django-software-foundation-2014/">Summary
          of 2014. </a>
      </p>

      <h2 id="who-are-the-django-fellows">Who are the Django Fellows?</h2>

      <p>There are currently two Django Fellows:</p>

      <p><strong><a href="https://github.com/carltongibson">Carlton Gibson</a>
        (2018-present)</strong> - a longtime Django user, core contributor to
        Django REST Framework, maintainer of Django Filter and Django Crispy
        Forms, and a contributor to many other packages in the Django ecosystem.
        Carlton <a href="https://www.djangoproject.com/weblog/2018/jan/12/dsf-welcomes-carlton-gibson-its-newest-fellow/">
        began as a part-time Fellow in January 2018</a>.</p>
      <p><strong><a href="https://github.com/felixxm">Mariusz Felisiak</a>
        (2019-present)</strong> - a member of the Django team since 2017,
        focusing on the ORM and Oracle back-end, along with triaging tickets,
        reviewing pull requests, and backporting changes. He has contributed to
        more than a dozen open-source projects. Mariusz
        <a href="https://www.djangoproject.com/weblog/2019/jan/29/dsf-welcomes-mariusz-felisiak-its-newest-fellow/">
        began as a full-time Fellow in April 2019</a>.
      </p>

      <p>Former Django Fellows:</p>

      <p><strong><a href="https://github.com/timgraham">Tim Graham</a> (2014-
        2019)</strong> - the inaugural Django Fellow, a member of the Django
        team since 2010, and a longtime major contributor and reviewer. In 2018
        Tim transitioned to part-time and in 2019 retired after four years of
        service.</p>
      <p><strong><a href="https://github.com/berkerpeksag">Berker Peksağ</a>
        (2014)</strong> - a core developer on CPython and Gunicorn, Berker
        worked as Fellow during the 3 month pilot, supporting Tim
        part-time.</p>
    </div>
  </div>
{% endblock %}

djangoproject/templates/fundraising/manage-donations.html
{% extends 'fundraising/index.html' %}
{% load static %}

{% block messages %}

  {% if messages %}
    {% for message in messages %}
    <p>{{ message }}</p>
    {% endfor %}
    <hr>
  {% endif %}

{% endblock %}

{% block content %}

<h1>Manage your donations to the Django Software Foundation</h1>
<p>Your support is <strong>invaluable</strong> to continue the rapid development
  of Django and helps the <strong>Django Fellowship</strong> program in particular.
  Thank you!</p>

<form enctype="multipart/form-data" action="" method="post" class="form-input django-hero-form"
    data-stripe-key="{{ stripe_publishable_key }}" data-stripe-icon="{% static 'img/dj-stripe-icon.jpg' %}"
    data-update-card-url="{% url 'fundraising:update-card' %}">
  <h2>Manage your participation in the fundraising campaigns</h2>
  <p>Information entered below will be visible on all of your donations to the Django Project.</p>
  {% csrf_token %}
  {% include 'fundraising/includes/_form.html' with form=hero_form %}
  <p class="submit">
    <input type="submit" class="cta" value="Save &rarr;">
  </p>
  {# Always include to avoid "Management form has been tampered with" if no recurring donations exist #}
  {{ modify_donations_formset.management_form }}
  {% if recurring_donations %}
    <hr />
    <h2>Modify your recurring donations</h2>
    <p>Update the time interval or amount of your recurring donation here:</p>
    {% for form in modify_donations_formset %}
      {% include 'fundraising/includes/_form.html' %}
      <div class="change-card-container">
        <input type="button" value="Change card details" class="change-card cta outline inline"
            data-donation-id="{{ form.instance.id }}" data-donor-email="{{ hero.email }}">
        <span class="change-card-result"></span>
      </div>
    {% endfor %}
    <p class="submit">
      <input type="submit" class="cta" value="Save &rarr;">
    </p>
</form>
    <hr />
    <h2>Cancel your recurring donations</h2>
    <p>You can cancel your recurring donation to the Django Software Foundation anytime.</p>
    <ul>
    {% for donation in recurring_donations %}
      <li>
        Your {{ donation.interval }} recurring donation of ${{ donation.subscription_amount }}.
        <form method="POST" action="{% url 'fundraising:cancel-donation' hero.pk %}">
          {% csrf_token %}
          <input name="donation" type="hidden" value="{{ donation.pk }}">
          <input type="submit" value="cancel this donation">
        </form>
      </li>
    {% endfor %}
    </ul>
  {% else %}
</form>
  {% endif %}
  {% if past_payments %}
  <hr />
    <h2>Your past donations</h2>
    <ul>
    {% for payment in past_payments %}
      <li>
        ${{ payment.amount }} on {{ payment.date|date:"N jS, Y \a\t P" }}
        ({{ payment.donation.get_interval_display }})
      </li>
    {% endfor %}
    </ul>
  {% endif %}
{% endblock %}

{% block content-extra %}{% endblock %}

djangoproject/templates/fundraising/thank-you.html
{% extends 'fundraising/index.html' %}
{% load humanize static %}

{% block content %}
<h1>Thank you for supporting the Django Project!</h1>
<p>Your support is <strong>invaluable</strong> to continue the rapid development
  of Django and helps the <strong>Django Fellowship</strong> program in particular.</p>

<p>Please help us spread the word and encourage your friends and colleagues to
  donate. Thank you!</p>

<a href="https://twitter.com/intent/tweet?button_hashtag=SupportDjango&text=I+just+donated+to+support+the+Django+Software+Foundation.+Join+me!+https%3A%2F%2Fwww.djangoproject.com%2Ffundraising%2F"
  class="twitter-hashtag-button" data-related="djangoproject">Tweet #SupportDjango</a>
<script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+'://platform.twitter.com/widgets.js';fjs.parentNode.insertBefore(js,fjs);}}(document, 'script', 'twitter-wjs');</script>

<p>
You should receive an email shortly, with confirmation of your donation,
details of badges you can display to show you support of Django, managing your
donation,  and how you can have your name or company displayed on the
Fundraising page and in the sidebar on the Django Project website.
</p>

<p>Welcome aboard! ⛵️</p>

<hr>

<p>If you have any <strong>problems</strong> with your donation please email <a href="mailto:donations@djangoproject.com">donations@djangoproject.com</a> for help.</p>

{% endblock %}

{% block content-extra %}{% endblock %}